"""Minimal interactive keypoint editor for every packaged shape family.

Renders one shape and its named points, lets you drag them with the mouse, and writes them back into
the shape's own SVG. Deliberately trivial — no error handling, no undo.

Usage::

    uv run python examples/edit_shape_keypoints.py duck
    uv run python examples/edit_shape_keypoints.py anchor
    uv run python examples/edit_shape_keypoints.py r

Called without a shape (or with an unknown one), it prints what is available and exits.

Two document shapes are handled, matching what each family actually stores:

**Outline families** (animals, symbols) draw a filled silhouette from their ``<path id="outline">``
with landmark dots on top. Dragging moves a landmark over a fixed silhouette; saving rewrites the
``keypoints`` group and regenerates the ``skeleton`` group from the new positions.

**The letter family** stores a stroke graph and no outline at all, so there is nothing to fill:
the strokes themselves are drawn as thick lines and the nodes are the dots. Dragging a node moves
the letter's actual geometry, since the silhouette is generated by stroking that graph at load time.
Saving rewrites the ``nodes`` group and re-syncs every ``strokes``/``cuts`` line's endpoints to it.

Controls: press and hold the left mouse button on a dot to drag it, release to drop · ``s`` saves
back into the SVG · ``q`` (or closing the window) quits. Saving always overwrites the shape's own
SVG in place — no dialog, no prompt. The color/name legend sits under the canvas.

"""

from __future__ import annotations

import os
import re
import xml.etree.ElementTree as ET
from collections.abc import Sequence
from dataclasses import dataclass, field
from pathlib import Path

import matplotlib.pyplot as plt
from matplotlib.axes import Axes
from matplotlib.figure import Figure
from matplotlib.lines import Line2D
from matplotlib.patches import Polygon as MplPolygon

# Importing the package pulls in whichever augmentation backends are installed; albumentations then
# calls PyPI at import time, which warns for seconds on a machine with no CA bundle. Nothing here
# needs that check, so switch it off before the import rather than live with the noise.
os.environ.setdefault("NO_ALBUMENTATIONS_UPDATE", "1")

# the schema *and* the path parser live in the package, not here — one definition for the loader, the
# writers and this editor, so a document the loader accepts (relative commands, H/V) is read the same
# way here instead of through a second, stricter parser that would silently misplace its vertices
from synth_datasets.families.animals import ANIMAL_KEYPOINT_NAMES, ANIMAL_KEYPOINT_SKELETON
from synth_datasets.families.letters import LETTER_KEYPOINT_NAMES
from synth_datasets.families.svgio import parse_path_d
from synth_datasets.families.symbols import SYMBOL_KEYPOINT_NAMES, SYMBOL_KEYPOINT_SKELETON

#: Fill color per point, written into every ``<circle>`` this editor saves. Lives here rather than
#: in the package because nothing in the library reads a fill — only this authoring tool does. A test
#: checks the packaged documents agree with themselves (one color per name within a family, none
#: shared), so a drift shows up without the library having to declare the palette.
ANIMAL_PALETTE = {
    "mouth": "#e6194b",
    "eye": "#ffe119",
    "ear": "#f58231",
    "head": "#911eb4",
    "neck": "#4363d8",
    "body_top": "#42d4f4",
    "body_bottom": "#3cb44b",
    "tail": "#f032e6",
    "front_elbow_left": "#bfef45",
    "front_elbow_right": "#ffd8b1",
    "front_limb_left": "#9a6324",
    "front_limb_right": "#fabed4",
    "hind_knee_left": "#808000",
    "hind_knee_right": "#aaffc3",
    "hind_limb_left": "#469990",
    "hind_limb_right": "#dcbeff",
}

#: The cycle the symbol and letter palettes are generated from, in the order their schema names them.
#: Those two families were converted from JSON literals rather than hand-coloured, so a positional
#: cycle is what their documents already carry.
_PALETTE_CYCLE = (
    "#e6194b",
    "#ffe119",
    "#f58231",
    "#911eb4",
    "#4363d8",
    "#42d4f4",
    "#3cb44b",
    "#f032e6",
    "#bfef45",
    "#ffd8b1",
    "#9a6324",
    "#fabed4",
    "#808000",
    "#aaffc3",
    "#469990",
)

DATA_DIR = Path(__file__).resolve().parents[1] / "src" / "synth_datasets"
SVG_NS = "http://www.w3.org/2000/svg"
ZOO_NS = "https://github.com/Borda/vision-synth/ns/zoo"
ET.register_namespace("", SVG_NS)
ET.register_namespace("zoo", ZOO_NS)


def _cycled_palette(names: Sequence[str]) -> dict[str, str]:
    """Return one color per name, cycling :data:`_PALETTE_CYCLE` in schema order."""
    return {name: _PALETTE_CYCLE[i % len(_PALETTE_CYCLE)] for i, name in enumerate(names)}


@dataclass(frozen=True)
class Family:
    """One editable shape family: where its documents live and how they are drawn.

    Args:
        name: The family's short name, used in the window title and the shape listing.
        directory: The packaged asset directory holding ``<shape>.svg``.
        point_names: Every point name the family's schema defines, in schema order.
        palette: Fill color per point name.
        group_id: The ``<g>`` the draggable circles live in — ``"keypoints"`` for an outline family,
            ``"nodes"`` for the letter graph.
        skeleton: Edges to draw between points, as index pairs into ``point_names``. Empty for the
            letter family, whose edges come from the document itself rather than from one shared
            topology.
        is_graph: Whether documents carry a stroke graph instead of an outline. This is the whole
            difference between the two rendering paths, so it is one flag rather than two classes.

    """

    name: str
    directory: Path
    point_names: tuple[str, ...]
    palette: dict[str, str]
    group_id: str
    skeleton: tuple[tuple[int, int], ...]
    is_graph: bool = False

    def shapes(self) -> list[str]:
        """Return every shape this family has a packaged document for."""
        return sorted(path.stem for path in self.directory.glob("*.svg"))


FAMILIES: tuple[Family, ...] = (
    Family(
        name="animals",
        directory=DATA_DIR / "assets" / "animals",
        point_names=ANIMAL_KEYPOINT_NAMES,
        palette=ANIMAL_PALETTE,
        group_id="keypoints",
        skeleton=ANIMAL_KEYPOINT_SKELETON,
    ),
    Family(
        name="symbols",
        directory=DATA_DIR / "assets" / "symbols",
        point_names=SYMBOL_KEYPOINT_NAMES,
        palette=_cycled_palette(SYMBOL_KEYPOINT_NAMES),
        group_id="keypoints",
        skeleton=SYMBOL_KEYPOINT_SKELETON,
    ),
    Family(
        name="letters",
        directory=DATA_DIR / "assets" / "letters",
        point_names=LETTER_KEYPOINT_NAMES,
        palette=_cycled_palette(LETTER_KEYPOINT_NAMES),
        group_id="nodes",
        skeleton=(),
        is_graph=True,
    ),
)


def find_family(shape: str) -> Family | None:
    """Return the family owning ``shape``, or ``None`` when no family has a document for it."""
    return next((family for family in FAMILIES if shape in family.shapes()), None)


@dataclass
class KeypointEditor:
    """Holds one shape's live editor state and handles its mouse/key events.

    Everything a handler needs to read or mutate — the landmark positions, the plotted artists, the SVG tree being
    edited — lives here instead of as closures over ``main``'s locals, so each handler is a plain method with an
    explicit ``self`` rather than a nested function capturing outer state.

    """

    shape: str
    family: Family
    svg_path: Path
    root: ET.Element
    points: dict[str, list[float]]
    fig: Figure
    dots: dict[str, Line2D]
    skeleton_lines: list[tuple[Line2D, str, str]]
    dragging: list[str] = field(default_factory=list)

    def refresh(self) -> None:
        """Redraw every dot and skeleton line from the current ``points`` positions."""
        for line, na, nb in self.skeleton_lines:
            line.set_data([self.points[na][0], self.points[nb][0]], [self.points[na][1], self.points[nb][1]])
        for name, dot in self.dots.items():
            dot.set_data([self.points[name][0]], [self.points[name][1]])
        self.fig.canvas.draw_idle()

    def on_press(self, event) -> None:
        """Latch the landmark nearest the click, if one is within 20 canvas units of it.

        Args:
            event: Matplotlib ``button_press_event``; ``xdata``/``ydata`` are ``None`` outside the axes.

        """
        self.dragging.clear()
        if event.xdata is None:
            return
        best, best_d2 = None, 20.0**2
        for name, (x, y) in self.points.items():
            d2 = (x - event.xdata) ** 2 + (y - event.ydata) ** 2
            if d2 < best_d2:
                best, best_d2 = name, d2
        if best:
            self.dragging.append(best)

    def on_drag(self, event) -> None:
        """Move the latched landmark to the cursor while the left button stays down.

        Args:
            event: Matplotlib ``motion_notify_event``; ``button`` is ``None`` for a plain hover.

        """
        # true drag-and-drop: the dot follows only while the mouse button is held down
        if self.dragging and event.button == 1 and event.xdata is not None:
            self.points[self.dragging[0]][:] = [event.xdata, event.ydata]
            self.refresh()

    def on_release(self, _event) -> None:
        """Drop the latched landmark, so the dot stops following the cursor.

        Args:
            _event: Matplotlib ``button_release_event``, unused — any release ends the drag.

        """
        self.dragging.clear()

    def on_key(self, event) -> None:
        """Handle ``q`` (close the window) and ``s`` (rewrite the shape's own SVG).

        Saving always overwrites the file in place and regenerates the skeleton lines from the new
        positions, so the derived group can never drift from the landmarks it draws.

        Args:
            event: Matplotlib ``key_press_event``; every other key is ignored.

        """
        if event.key == "q":
            plt.close(self.fig)
        if event.key != "s":
            return
        self._save()

    def _save(self) -> None:
        """Rewrite the document's point group from ``points``, plus whatever else derives from it."""
        if self.family.is_graph:
            self._save_graph()
        else:
            self._save_outline()
        out = ET.tostring(self.root, encoding="unicode")
        out = re.sub(r"><", ">\n  <", out)
        self.svg_path.write_text(out if out.endswith("\n") else out + "\n")
        self.fig.canvas.manager.set_window_title(f"{self.family.name} — {self.shape}  [saved]")

    def _circle_group(self) -> ET.Element:
        """Build the family's point group as a fresh ``<g>`` of named, colored circles."""
        group = ET.Element(f"{{{SVG_NS}}}g", {"id": self.family.group_id})
        for name in self.family.point_names:
            if name not in self.points:
                continue
            x, y = self.points[name]
            ET.SubElement(
                group,
                f"{{{SVG_NS}}}circle",
                {
                    "id": f"kp-{name}",
                    f"{{{ZOO_NS}}}name": name,
                    "cx": f"{x:.3f}",
                    "cy": f"{y:.3f}",
                    "r": "8",
                    "fill": self.family.palette[name],
                    "stroke": "#ffffff",
                    "stroke-width": "1.5",
                },
            )
        return group

    def _save_outline(self) -> None:
        """Rewrite the ``keypoints`` group, regenerating ``skeleton`` from the new positions.

        The skeleton is derived, never edited, so it is rebuilt rather than patched — that is what stops it drifting
        from the landmarks it draws.

        """
        for group_id in (self.family.group_id, "skeleton"):
            group = self.root.find(f"{{{SVG_NS}}}g[@id='{group_id}']")
            if group is not None:
                self.root.remove(group)
        skeleton = ET.Element(f"{{{SVG_NS}}}g", {"id": "skeleton"})
        for a, b in self.family.skeleton:
            na, nb = self.family.point_names[a], self.family.point_names[b]
            if na in self.points and nb in self.points:
                (x1, y1), (x2, y2) = self.points[na], self.points[nb]
                ET.SubElement(
                    skeleton,
                    f"{{{SVG_NS}}}line",
                    {
                        "x1": f"{x1:.0f}",
                        "y1": f"{y1:.0f}",
                        "x2": f"{x2:.0f}",
                        "y2": f"{y2:.0f}",
                        "stroke": "#34c759",
                        "stroke-width": "3",
                        "stroke-linecap": "round",
                    },
                )
        self.root.append(skeleton)
        self.root.append(self._circle_group())

    def _save_graph(self) -> None:
        """Rewrite the ``nodes`` group and re-sync every stroke/cut line's endpoints to it.

        A graph document's lines carry both the node names (which the loader reads) and drawn coordinates (which only a
        viewer reads). Only the names are load-bearing, but leaving the coordinates stale would make the file render as
        something other than what it loads as — so they are recomputed here from the very positions being saved.

        """
        for group_id in ("strokes", "cuts"):
            group = self.root.find(f"{{{SVG_NS}}}g[@id='{group_id}']")
            if group is None:
                continue
            for line in group.findall(f"{{{SVG_NS}}}line"):
                start, end = line.get(f"{{{ZOO_NS}}}start"), line.get(f"{{{ZOO_NS}}}end")
                if start in self.points and end in self.points:
                    (x1, y1), (x2, y2) = self.points[start], self.points[end]
                    line.set("x1", f"{x1:.3f}")
                    line.set("y1", f"{y1:.3f}")
                    line.set("x2", f"{x2:.3f}")
                    line.set("y2", f"{y2:.3f}")
        nodes = self.root.find(f"{{{SVG_NS}}}g[@id='{self.family.group_id}']")
        if nodes is not None:
            self.root.remove(nodes)
        self.root.append(self._circle_group())


def _draw(
    shape: str, family: Family, root: ET.Element, points: dict[str, list[float]]
) -> tuple[Figure, Axes, dict[str, Line2D], list[tuple[Line2D, str, str]]]:
    """Build the figure, axes, and initial artists for ``shape``'s geometry and points."""
    # drop matplotlib's own "s = save figure" / "q = quit" bindings so this script owns those keys
    plt.rcParams["keymap.save"] = []
    plt.rcParams["keymap.quit"] = []

    fig, ax = plt.subplots(figsize=(9, 9))
    fig.canvas.manager.set_window_title(f"{family.name} — {shape}")
    ax.set_xlim(0, 1000)
    ax.set_ylim(1000, 0)  # SVG y grows downward
    ax.set_aspect("equal")
    ax.set_xticks([])
    ax.set_yticks([])
    ax.set_title(
        f"{shape} — press & hold a dot to drag, release to drop  ·  s = save into SVG  ·  q = quit",
        fontsize=10,
    )

    skeleton_lines = _draw_geometry(ax, shape, family, root, points)

    dots = {}
    for name, (x, y) in points.items():
        (dot,) = ax.plot(
            x,
            y,
            "o",
            markersize=11,
            markerfacecolor=family.palette[name],
            markeredgecolor="white",
            zorder=3,
            label=name,
        )
        dots[name] = dot

    # color/name legend under the canvas instead of a label glued to every dot
    ax.legend(loc="upper center", bbox_to_anchor=(0.5, -0.01), ncol=6, fontsize=8, framealpha=0.9)
    fig.subplots_adjust(left=0.02, right=0.98, top=0.95, bottom=0.1)

    return fig, ax, dots, skeleton_lines


def _draw_geometry(
    ax: Axes, shape: str, family: Family, root: ET.Element, points: dict[str, list[float]]
) -> list[tuple[Line2D, str, str]]:
    """Draw the shape itself and return the editable connecting lines.

    An outline family gets a filled silhouette plus thin skeleton lines that are purely a viewing aid. The letter family
    has no silhouette to fill — its strokes *are* its geometry — so those are drawn thick, and dragging a node visibly
    reshapes the letter rather than sliding a dot over a fixed picture.

    """
    if family.is_graph:
        lines: list[tuple[Line2D, str, str]] = []
        for group_id, width, color in (("strokes", 14, "#111111"), ("cuts", 3, "#ff3b30")):
            group = root.find(f"{{{SVG_NS}}}g[@id='{group_id}']")
            if group is None:
                continue
            for element in group.findall(f"{{{SVG_NS}}}line"):
                na, nb = element.get(f"{{{ZOO_NS}}}start"), element.get(f"{{{ZOO_NS}}}end")
                if na not in points or nb not in points:
                    continue
                (line,) = ax.plot(
                    [points[na][0], points[nb][0]],
                    [points[na][1], points[nb][1]],
                    color=color,
                    linewidth=width,
                    solid_capstyle="round",
                    zorder=1 if width > 5 else 2,
                )
                lines.append((line, na, nb))
        return lines

    outline = parse_path_d(root.find(f"{{{SVG_NS}}}path[@id='outline']").get("d"), shape)
    ax.add_patch(MplPolygon(outline, closed=True, facecolor="black", zorder=1))
    lines = []
    for a, b in family.skeleton:
        na, nb = family.point_names[a], family.point_names[b]
        if na in points and nb in points:
            (line,) = ax.plot(
                [points[na][0], points[nb][0]],
                [points[na][1], points[nb][1]],
                color="#34c759",
                linewidth=2,
                zorder=2,
            )
            lines.append((line, na, nb))
    return lines


def main(shape: str = "") -> None:
    """Open the interactive editor for the named shape, or list valid names."""
    family = find_family(shape) if shape else None
    if family is None:
        listing = "\n".join(f"  {fam.name}: {', '.join(fam.shapes())}" for fam in FAMILIES)
        print(f"unknown shape {shape or '(nothing)'!r} — pick one of:\n{listing}")
        raise SystemExit(1)

    svg_path = family.directory / f"{shape}.svg"
    root = ET.fromstring(svg_path.read_text())

    points: dict[str, list[float]] = {}
    for circle in root.find(f"{{{SVG_NS}}}g[@id='{family.group_id}']").findall(f"{{{SVG_NS}}}circle"):
        points[circle.get(f"{{{ZOO_NS}}}name")] = [float(circle.get("cx")), float(circle.get("cy"))]

    fig, _ax, dots, skeleton_lines = _draw(shape, family, root, points)
    editor = KeypointEditor(
        shape=shape,
        family=family,
        svg_path=svg_path,
        root=root,
        points=points,
        fig=fig,
        dots=dots,
        skeleton_lines=skeleton_lines,
    )

    fig.canvas.mpl_connect("button_press_event", editor.on_press)
    fig.canvas.mpl_connect("motion_notify_event", editor.on_drag)
    fig.canvas.mpl_connect("button_release_event", editor.on_release)
    fig.canvas.mpl_connect("key_press_event", editor.on_key)
    print("controls: press & hold a dot to drag, release to drop · s = save into SVG · q = quit")
    plt.show()


if __name__ == "__main__":
    import fire

    fire.Fire(main)
